# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rashEihPvTEiYfy1F3qJKJWoWRqr1kjc
"""

# Case Study 1 - House Price Prediction
# Step 1: Import Libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

# Step 2a: Load Dataset
data = pd.read_csv("PSCaseStudy1_Dataset.csv")

# Step 3: Visualize the Dataset
plt.scatter(data["Area"], data["Price"])
plt.xlabel("Area (sq ft)")
plt.ylabel("Price")
plt.title("House Price Dataset")
plt.show()

# Step 4: Prepare Data and Train Linear Model
X = data[['Area']]
y = data['Price']

linear_model = LinearRegression()
linear_model.fit(X, y)

y_pred_linear = linear_model.predict(X)

# Step 5: Visualize Linear Regression Fit
plt.scatter(X, y)
plt.plot(X, y_pred_linear, color='red')
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("Linear Regression Fit")
plt.show()

# Step 6: Evaluate Linear Model
mse_linear = mean_squared_error(y, y_pred_linear)
print("Linear Regression MSE:", mse_linear)

rmse_linear = np.sqrt(mse_linear)
print("Linear Regression RMSE:", rmse_linear)

# Step 7: Polynomial Regression
poly = PolynomialFeatures(degree=10)
X_poly = poly.fit_transform(X)

poly_model = LinearRegression()
poly_model.fit(X_poly, y)

y_pred_poly = poly_model.predict(X_poly)

# Step 8: Visualize Polynomial Fit
sorted_zip = sorted(zip(X["Area"], y_pred_poly))
X_sorted, y_poly_sorted = zip(*sorted_zip)

plt.scatter(X, y)
plt.plot(X_sorted, y_poly_sorted, color='green')
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("Polynomial Regression Fit")
plt.show()